In [1]:
import numpy as np 

# Array Creation

In [2]:
# create numpy array 
a = np.array([[1, 2, 3],[1,2,3]])

In [3]:
# get number of dimentions of a array
a.ndim

2

In [4]:
# get shape of numpy array
a.shape

(2, 3)

In [5]:
# get the type of items in the array
a.dtype

dtype('int64')

In [6]:
# create arrays with initial zero-valued placeholders
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# create arrays with initial one-valued placeholders
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# # create arrays with some initial placeholders
np.full(a.shape,255)

array([[255, 255, 255],
       [255, 255, 255]])

In [9]:
# generate an array with random numbers
np.random.rand(2,3)

array([[0.0014937 , 0.9876319 , 0.86459049],
       [0.89172887, 0.07427703, 0.98923514]])

In [10]:
# create a sequence of numbers in an array
np.arange(10, 50, 2) # create an array of every even number from ten (inclusive) to fifty (exclusive)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
# create a sequence of n unmber form a to b -> np.linspace(a,b,n)
np.linspace( 0, 2, 15 ) # 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [12]:
# reshape an array 
np.arange(1,16,1).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Array Operations

In [13]:
a = np.array([10,20,30,40])
b = np.array([5, 25, 125,200])

In [14]:
# Arithmetic operators on array apply elementwise
b+a # for example b plus a 

array([ 15,  45, 155, 240])

In [15]:
# to get a boolean array to check conditional things
b < a

array([ True, False, False, False])

In [16]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [17]:
# elementwise product
A*B

array([[2, 0],
       [0, 4]])

In [18]:
# to do matrix product
A@B

array([[5, 4],
       [3, 4]])

In [19]:
# to do matrix product
np.dot(A,B)

array([[5, 4],
       [3, 4]])

## statistical functions 

In [20]:
# sum of elements of the matrix
B.sum()

9

In [21]:
# max value of the matrix 
B.max()

4

In [22]:
# min value of the matrix 
B.min()

0

In [23]:
# mean of elements of the matrix
B.mean()

2.25

# indexing

In [26]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# if we want to get multiple elements 
# we can enter the indices directly into an array function
np.array([a[0, 0], a[1, 1], a[2, 1]])

array([1, 4, 6])

In [28]:
# we can also do that by using another form of array indexing, which essentiall "zips" the first list and the
# second list up
a[[0, 1, 2], [0, 1, 1]]

array([1, 4, 6])

In [30]:
# We can then place this array of booleans like a mask over the original array to return a one-dimensional 
# array relating to the true values.
print(a[a>4])

[5 6]


# slicing 

In [31]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [32]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

# check nan-valued in numpy

In [2]:
# we can not compare NaN with None 

np.nan == None

False

In [3]:
# we can't do an equality test of NAN to itself

np.nan == np.nan

False

In [4]:
# we must check NaN with some functions like isnan in numpy

np.isnan(np.nan)

True